#!/usr/bin/env python3
"""Fetch the candela WebAssembly runtime for the Candela landing's prompt.

The landing runs candela in the browser. The runtime it loads is the `web`
asset attached to a candela release, so the prompt on the site and the
toolchain a visitor installs are built from the same source at the same
version. Nothing is compiled here and no Rust toolchain is needed.

The asset is a tarball holding the wasm-bindgen output:

    candela.js          the module that loads the runtime
    candela_bg.wasm     the runtime

Both land in apps/candela/public/runtime/, which `vite build` copies to
/runtime/ in the deployed site. The download size the page quotes is measured
from the file itself and written to a generated module, so it cannot drift.

Run this before `vite build` (scripts/build.sh and CI both do).

Environment overrides:
  CANDELA_WASM_DIR   use a local wasm-bindgen output directory instead of a
                     release asset. Point it at the `pkg` directory a local
                     `wasm-pack build --target web` produced. This is how the
                     site is built before a release carries the asset.
  CANDELA_WASM_TAG   release tag to take the asset from (default: latest)
  CANDELA_REPO       the candela repository, for both of the above
"""

from __future__ import annotations

import json
import os
import shutil
import sys
import tarfile
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNTIME = ROOT / "apps" / "candela" / "public" / "runtime"
GENERATED = ROOT / "apps" / "candela" / "src" / "generated" / "runtime.ts"

REPO = os.environ.get("CANDELA_REPO", "https://github.com/lumen-fx/candela")
TAG = os.environ.get("CANDELA_WASM_TAG", "latest")
LOCAL = os.environ.get("CANDELA_WASM_DIR")

WANTED = ("candela.js", "candela_bg.wasm")


def api_slug(repo: str) -> str:
    """owner/name, from a git URL or an owner/name string."""
    trimmed = repo.rstrip("/").removesuffix(".git")
    if trimmed.startswith("http"):
        return "/".join(trimmed.split("/")[-2:])
    return trimmed


def release_asset_url() -> tuple[str | None, str]:
    """The web asset's download URL and the tag it came from.

    The URL is None when that release has no web asset, which every release cut
    before the asset existed is.
    """
    slug = api_slug(REPO)
    path = "releases/latest" if TAG == "latest" else f"releases/tags/{TAG}"
    url = f"https://api.github.com/repos/{slug}/{path}"
    request = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json"})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        request.add_header("Authorization", f"Bearer {token}")

    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            release = json.load(response)
    except urllib.error.HTTPError as error:
        sys.exit(
            f"error: cannot read the candela release ({error}).\n"
            f"       Set CANDELA_WASM_DIR to a local `wasm-pack build --target web` "
            f"output directory to build the site without one."
        )

    for asset in release.get("assets", []):
        name = asset.get("name", "")
        if name.startswith("candela-web") and name.endswith(".tar.gz"):
            return asset["browser_download_url"], release.get("tag_name", TAG)
    return None, release.get("tag_name", TAG)


def take_from(directory: Path, source: str) -> None:
    """Copy the runtime files out of a wasm-bindgen output directory."""
    RUNTIME.mkdir(parents=True, exist_ok=True)
    for name in WANTED:
        found = directory / name
        if not found.is_file():
            sys.exit(f"error: {name} not found in {directory}; is that a --target web build?")
        shutil.copyfile(found, RUNTIME / name)
    emit(source)


def emit(source: str) -> None:
    """Write the module carrying the runtime's measured size."""
    size = (RUNTIME / "candela_bg.wasm").stat().st_size
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(
        "// Generated by scripts/fetch_candela_wasm.py. Do not edit.\n"
        "// Measured from the runtime this build fetched, so the page cannot\n"
        "// quote a size the file does not have.\n"
        f"\n// {source}\n"
        f"export const WASM_BYTES = {size};\n",
        encoding="utf-8",
    )
    print(f"candela runtime @ {source} -> {RUNTIME.relative_to(ROOT)} ({size} bytes)", flush=True)


def without_runtime(tag: str) -> None:
    """Build the site with no runtime to load.

    Releases cut before the web asset existed do not carry one, so this is the
    normal state until the next release. The page already handles a runtime it
    cannot load: the prompt reads back as a transcript and says so. Say it here
    too, loudly, rather than failing every build in the meantime.
    """
    for name in WANTED:
        (RUNTIME / name).unlink(missing_ok=True)
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    GENERATED.write_text(
        "// Generated by scripts/fetch_candela_wasm.py. Do not edit.\n"
        "// No release carried the web asset when this site was built, so the\n"
        "// prompt has no runtime to load and says so on the page.\n"
        "\nexport const WASM_BYTES = 0;\n",
        encoding="utf-8",
    )
    print(
        f"warning: candela {tag} has no candela-web asset, so the landing ships without a\n"
        f"         runtime and its prompt will read back as a transcript. Cut a candela\n"
        f"         release carrying the asset, or set CANDELA_WASM_DIR to a local build.",
        flush=True,
    )


def main() -> None:
    if LOCAL:
        # No path in the source line: this file is committed, and a developer's
        # directory layout is not something the repository should carry.
        take_from(Path(LOCAL).expanduser(), "a local build")
        return

    url, tag = release_asset_url()
    if url is None:
        without_runtime(tag)
        return
    with tempfile.TemporaryDirectory() as tmp:
        archive = Path(tmp) / "candela-web.tar.gz"
        print(f"+ download {url}", flush=True)
        urllib.request.urlretrieve(url, archive)
        unpacked = Path(tmp) / "unpacked"
        with tarfile.open(archive) as tar:
            # The asset is ours, but an archive is still untrusted input: refuse
            # any member that would write outside the directory it unpacks into.
            for member in tar.getmembers():
                target = (unpacked / member.name).resolve()
                if not str(target).startswith(str(unpacked.resolve())):
                    sys.exit(f"error: {member.name} escapes the archive root")
            tar.extractall(unpacked)

        candidates = [p for p in unpacked.rglob("candela_bg.wasm")]
        if not candidates:
            sys.exit("error: the candela-web asset has no candela_bg.wasm")
        take_from(candidates[0].parent, f"candela {tag}")


if __name__ == "__main__":
    main()
