#!/usr/bin/env python3
"""Assemble the docs_dir and generate the Zensical config for each Zensical target.

The site has three static builds. Two are Zensical -- apex (the Lumen landing)
and docs (the unified docs) -- and share one theme; this script prepares those.
The third, the Candela landing, is a separate Vite + React app under apps/candela
(built with npm, not Zensical), so it is not handled here.

Each Zensical target has its own docs_dir (site source) and its own generated
config. Product docs are fetched fresh from each product repo at build time and
are never committed to this repo. Run this before `zensical build`.

For each target this script:

  1. Assembles build/<target>/docs (the Zensical docs_dir) from:
       * content/shared/    theme assets (stylesheets, favicon), copied to
                            every target.
       * content/<target>/  the target's own pages (landing or docs home,
                            stubs), copied verbatim.
       * cloned product docs (docs target only) copied to a subpath.
  2. Writes zensical.<target>.toml at the repo root by concatenating the
     target's [project] block (config/<target>.toml) in front of the shared
     theme (config/theme.toml). The config is written at the repo root so
     Zensical resolves docs_dir and site_dir relative to the repo root.

Adding Lumen docs later is a one-line change: add a clone entry to the docs
target's "clones" list once the Lumen docs are Zensical markdown (they are an
mdbook today).

Environment overrides:
  CANDELA_REPO   git URL for candela        (default: the public GitHub repo)
  CANDELA_REV    branch, tag, or commit SHA (default: main)
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
SHARED = CONTENT / "shared"
CONFIG = ROOT / "config"
THEME_FRAGMENT = CONFIG / "theme.toml"
BUILD = ROOT / "build"
REPOS = BUILD / "repos"


# A clone entry pulls a product repo at a rev and copies a subdirectory of
# markdown into the target's docs_dir. This is how the docs target picks up the
# Candela docs. To add Lumen once its docs are Zensical markdown, append an
# entry to the docs target's "clones" and add the nav in config/docs.toml.
def _candela_clone() -> dict:
    return {
        "name": "candela",
        "repo": os.environ.get("CANDELA_REPO", "https://github.com/lumen-fx/candela"),
        "rev": os.environ.get("CANDELA_REV", "main"),
        # Subpath of the cloned repo that holds the markdown docs.
        "src_subdir": Path("docs") / "docs",
        # Destination under the target's docs_dir (served at /candela/).
        "dest_subdir": Path("candela"),
    }


# The three build targets. Each becomes its own static site rooted at "/".
TARGETS = [
    {
        # Lumen landing at the root of lumenfx.dev.
        "name": "apex",
        "content_dir": CONTENT / "apex",
        "clones": [],
    },
    {
        # Unified docs at the root of docs.lumenfx.dev.
        "name": "docs",
        "content_dir": CONTENT / "docs",
        "clones": [
            _candela_clone(),
            # When the Lumen docs move to Zensical, add:
            # {
            #     "name": "lumen",
            #     "repo": os.environ.get("LUMEN_REPO", "https://github.com/lumen-fx/lumen"),
            #     "rev": os.environ.get("LUMEN_REV", "main"),
            #     "src_subdir": Path("docs"),
            #     "dest_subdir": Path("lumen"),
            # },
        ],
    },
]


def run(cmd: list, **kw) -> None:
    print("+", " ".join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], check=True, **kw)


def clone(repo: str, rev: str, dest: Path) -> None:
    """Fetch a single rev (branch, tag, or SHA) shallowly into dest."""
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)
    run(["git", "init", "-q", dest])
    run(["git", "-C", dest, "remote", "add", "origin", repo])
    run(["git", "-C", dest, "fetch", "-q", "--depth", "1", "origin", rev])
    run(["git", "-C", dest, "checkout", "-q", "FETCH_HEAD"])


def generate_config(target: str) -> Path:
    """Write zensical.<target>.toml at the repo root: per-target block + theme."""
    part = CONFIG / f"{target}.toml"
    if not part.is_file():
        sys.exit(f"error: missing target config: {part}")
    if not THEME_FRAGMENT.is_file():
        sys.exit(f"error: missing theme fragment: {THEME_FRAGMENT}")
    out = ROOT / f"zensical.{target}.toml"
    header = (
        f"# GENERATED by scripts/prebuild.py from config/{target}.toml and\n"
        f"# config/theme.toml. Do not edit; edit those sources instead.\n\n"
    )
    body = (
        part.read_text(encoding="utf-8").rstrip()
        + "\n\n"
        + THEME_FRAGMENT.read_text(encoding="utf-8")
    )
    out.write_text(header + body, encoding="utf-8")
    print(f"generated config -> {out.relative_to(ROOT)}", flush=True)
    return out


def assemble_target(target: dict) -> None:
    name = target["name"]
    docs_out = BUILD / name / "docs"
    if docs_out.exists():
        shutil.rmtree(docs_out)
    docs_out.mkdir(parents=True)

    # Shared theme assets first (stylesheets, favicon), then the target's own
    # pages on top.
    if not SHARED.is_dir():
        sys.exit(f"error: missing shared assets directory: {SHARED}")
    shutil.copytree(SHARED, docs_out, dirs_exist_ok=True)

    content_dir = target["content_dir"]
    if not content_dir.is_dir():
        sys.exit(f"error: missing content directory: {content_dir}")
    shutil.copytree(content_dir, docs_out, dirs_exist_ok=True)
    print(
        f"[{name}] seeded docs_dir from "
        f"{SHARED.relative_to(ROOT)} + {content_dir.relative_to(ROOT)}",
        flush=True,
    )

    for src in target["clones"]:
        clone_dest = REPOS / f"{name}-{src['name']}"
        clone(src["repo"], src["rev"], clone_dest)
        md_src = clone_dest / src["src_subdir"]
        if not md_src.is_dir():
            sys.exit(f"error: {src['name']} docs not found at {md_src}")
        md_dest = docs_out / src["dest_subdir"]
        shutil.copytree(md_src, md_dest, dirs_exist_ok=True)
        print(
            f"[{name}] copied {src['name']} docs @ {src['rev']} "
            f"-> {md_dest.relative_to(ROOT)}",
            flush=True,
        )

    generate_config(name)
    print(f"[{name}] docs_dir assembled at {docs_out.relative_to(ROOT)}", flush=True)


def main() -> None:
    if not CONTENT.is_dir():
        sys.exit(f"error: missing content directory: {CONTENT}")
    for target in TARGETS:
        assemble_target(target)


if __name__ == "__main__":
    main()
